all: partial.vo namesAndTypes.vo syntax.vo classTable.vo heap.vo sframe.vo reductions.vo typing.vo

# This part is generated by "coqdep *.v"
classTable.vo : classTable.v syntax.vo partial.vo namesAndTypes.vo
	coqc $<
heap.vo : heap.v namesAndTypes.vo
	coqc $<
namesAndTypes.vo : namesAndTypes.v partial.vo
	coqc $<
partial.vo : partial.v
	coqc $<
preservation.vo : preservation.v syntax.vo partial.vo heap.vo classTable.vo sframe.vo reductions.vo typing.vo
	coqc $<
reductions.vo : reductions.v syntax.vo partial.vo heap.vo classTable.vo sframe.vo namesAndTypes.vo
	coqc $<
sframe.vo : sframe.v syntax.vo partial.vo heap.vo classTable.vo namesAndTypes.vo
	coqc $<
syntax.vo : syntax.v partial.vo namesAndTypes.vo
	coqc $<
typing.vo : typing.v syntax.vo partial.vo heap.vo classTable.vo sframe.vo reductions.vo
	coqc $<



